# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91e45bdce68cbd60065bfb1bee3b6041e2456aa8cdc833c27bbba8bfda2e3e66eb550be6b2c39e14c7af7d7a13bc634f3af2a43f756d56593c068e9b3625821

test:
  secret_key_base: c3240e65ba31fd637bd2cf4a09217490a8930c5948cd55ee1fcaa88e8e33c4860f4ea74d54080b3614f629d429884b5b3c9e4a46887df08912fb2d4b37ec3424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
